### ISSUE TITLE
convert_scmdf_to_tuningstruc: reverse dimensions of data

### ISSUE THREAD

**Issue by NortonAlex** [znicholls/netcdf-scm#110]
The convert_scmdf_to_tuningstruc routine writes the .mat "data" field with the dimensions around the wrong way.

In the final .mat structure, the field "data" should consist of two columns (years,data), but instead it is two rows. Should be an easy transpose fix :)

Please put the code (ideally in the form of a unit
test) which fails below

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

 - OS: [e.g. Windows, Linux, macOS]
 - Python version [e.g. Python 3.5] and output of `conda list --export` and `pip freeze` as applicable

**Additional context**

**Comment by znicholls** [comment]
Ok cool no worries that's an easy fix. We did have it the other way round then had to reverse that for some reason I can't remember. I think you're the only user now so will swap and see what happens.
