### ISSUE TITLE
license to use

### ISSUE THREAD

**Issue by znicholls** [znicholls/netcdf-scm#2]
I have no idea about this, @rgieseke or @lewisjared do you have an idea about what's best?

**Comment by znicholls** [comment]
why does pymagicc have GNU Affero General Public License v3.0

**Comment by rgieseke** [comment]
AGPL ensures that code needs to be shared *even* when Pymagicc is running on a server for a website. WIth GPL the code needs to be shared only when e.g. a binary were be passed. For a model where you want greatest transparency I think AGPL is a good choice (eve though here it is only the wrapper).

For "infrastructure" code BSD or MIT (which can be mixed with GPL code) seems a good choice. It should be possible to incorporate into any project later. With GPL code you might be able to incorporate it into a MIT licensed project so easily (without asking all authors to agree to a license change).
