### ISSUE TITLE
Validate with CMIP5 output from AR5 WGI report

### ISSUE THREAD

**Issue by rgieseke** [znicholls/netcdf-scm#21]
Yearly `tas` timeseries are available in the appendix of AR5 WGI report:

http://www.climatechange2013.org/report/full-report/

Atlas of Global and Regional Climate Projections 44.7MB, EndNote/BibTeX
    Supplementary Material: RCP2.6, RCP4.5, RCP6.0, RCP8.5, datafiles
    IPCC WGI AR5 Atlas datasets included in KNMI Climate Change Atlas

ZIP Download:
http://www.climatechange2013.org/images/report/WGIAR5_AnnexI_all.zip

From the PDF:

Data  and  Processing:
> The  figures  have  been  constructed  using  the CMIP5  model  output  available  at  the  time  of  the  AR5  cut-off  for accepted papers (15 March 2013). This data set comprises 32/42/25/39
scenario  experiments  for  RCP2.6/4.5/6.0/8.5  from  42  climate  models (Table  AI.SM2.6.1).  Only  concentration-driven  experiments  are  used (i.e.,  those  in  which  concentrations  rather  than  emissions  of  green-house  gases  are  prescribed)  and  only  one  ensemble  member  from each model is selected, even if multiple realizations exist with different  initial  conditions  and  different  realizations  of  natural  variability. Hence each model is given equal weight.

It might be possible to get the used model/run combo from this table
>Table AI.SM2.6.1 |  
> The CMIP5 models used in this Annex for each of the historical and RCP scenario experiments. A number in each column is the identifier of the single ensemble 
member from that model that is used. A blank indicates no run was used, usually because that scenario run was not available.

If you have ideas on how to include this as a verification of your code, let me know @znicholls !

**Comment by znicholls** [comment]
Wicked. As step 1, can you make a PR which adds the model mean data for whatever scenarios are in there to the repo (model data is useless as its unlabelled)?

**Comment by rgieseke** [comment]
What do the numbers in Table AI.1 in http://www.climatechange2013.org/images/report/WG1AR5_AnnexI_FINAL.pdf refer to?

**Comment by znicholls** [comment]
The 'X' number in 'rXi1p1', i.e. which realisation of the scenario was
included in the mean.

**Comment by rgieseke** [comment]
Doesn't
>only one ensemble member from each model is selected, even if multiple realizations exist with different initial conditions and different realizations of natural variability. Hence each model is given equal weight.
mean, that this should be the number of the realisation?

**Comment by znicholls** [comment]
Closed by #29
