### ISSUE TITLE
Logging refresh

### ISSUE THREAD

**Issue by lewisjared** [znicholls/netcdf-scm#51]
**Is your feature request related to a problem? Please describe.**

We need a way to keep track of the files used when crunching to CSV. This provides traceability and the ability to perform smart updating in future when new land area masks become available.

These files will replace the `*-failures-and-warnings.txt` files written in the root of a dataset.

**Describe the solution you'd like**

* [x] Database of crunched files which is flushed to disk after every crunch. Entries include updated_at, in_files, out_file
* [x] Database becomes the authority regarding recrunching
* [x] Smarter progress bars
* [x] Log everything to disk

**Comment by znicholls** [comment]
@lewisjared we can close this right?
