### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by znicholls** [znicholls/netcdf-scm#6]
**Is your feature request related to a problem? Please describe.**

Running this code always through a Python session or a notebook is overly slow, a command line interface would super nice.

**Describe the solution you'd like**

Use the packages described in [this blog post](https://stormpath.com/blog/building-simple-cli-interfaces-in-python) and also add in a few other tricks they recommend (making sure to update docs as well as CI etc. when doing this).

**Describe alternatives you've considered**

No command line options...

**Comment by lewisjared** [comment]
I have a base for creating new commands in #31 
Each command is represented as a class which inherits `BaseCommand`. This keeps the code, arguments and documentation stay in one place and makes it easy to define new commands.

While I was away I created a CLI tool for managing the backups of the various instruments on board which used a very similar pattern [lewisjared/airbox](https://github.com/lewisjared/airbox)
