### ISSUE TITLE
Move test nc files to lfs

### ISSUE THREAD

**Issue by znicholls** [znicholls/netcdf-scm#83]
https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs

Follow advice here (https://github.com/git-lfs/git-lfs/issues/3238#issuecomment-448662851) to ensure that gitattributes file is consistent across all history before doing migration

**Comment by znicholls** [comment]
@lewisjared I'm going to do this tomorrow so when you're back you'll need a fresh clone!

**Comment by znicholls** [comment]
This is done, clone without pulling all the lfs history with `GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:znicholls/netcdf-scm.git netcdf-scm`

**Comment by znicholls** [comment]
I lie this is way harder than I thought

**Comment by lewisjared** [comment]
Ahh lfs...

**Comment by znicholls** [comment]
This is now done, can clone with `GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:znicholls/netcdf-scm.git` to avoid pulling all the lfs files straight away. 

Insanely, the solution was to run the following (which is slow but neither bfg or git lfs migrate could handle the `.gitattributes` files popping up halfway through the repo's history).

```
git filter-branch -f --prune-empty --tree-filter '
git rm -f ./**.gitattributes
cp -v /Users/znicholls/.gitattributes ./.gitattributes
git lfs install
git lfs track "tests/**/*.nc"
git lfs track "tests/**/*.mat"
git add .gitattributes

for file in $(git ls-files | xargs git check-attr filter | grep "filter: lfs" | sed -r "s/(.*): filter: lfs/\1/"); do
    echo "Processing ${file}"

    git rm -f --cached ${file}
    echo "Adding $file lfs style"
    git add ${file}
done' --tag-name-filter cat -- --all
```
